### ISSUE TITLE
Authentik - "User is undefined" when setting up MAS

### ISSUE THREAD

**Issue by wjbeckett** [element-hq/matrix-authentication-service#3383]
**Describe the bug**
I am attempting to setup MAS with ansible (utilising the spantaleev playbook). After configuring the playbook and my upstream oidc (Authentik) and rubbing the playbook to set it up, I get an error saying User is undefined. This is referring to the claim template from what I can tell.

**Additional context**
CONSOLE ERROR:
[{''id'': ''01HFRQFT5QFMJFGF01P7JAV2ME'', ''human_name'': ''Authentik'', ''issuer'': ''https://auth.REDACTED/application/o/mas/'', ''client_id'': ''REDACTED'', ''client_secret'': ''REDACTED'', ''scope'': ''openid profile email'', ''claims_imports'': {''localpart'': {''action'': ''require'', ''template'':
    ''{{ user.preferred_username }}''}, ''displayname'': {''action'': ''suggest'', ''template'': ''{{ user.name }}''}, ''email'': {''action'': ''suggest'', ''template'': ''{{ user.email }}'', ''set_email_verification'': ''always''}}}]: ''user'' is undefined. ''user'' is undefined'

**Comment by spantaleev** [comment]
Here's the corresponding [issue on our side](https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/3645).

MAS seems to be fine - Jinja templating was choking on values like `{{ user.name }}`, so we now instruct people to wrap them with `{% raw %}` and `{% endraw %}`.

MAS is fine. This issue can be closed.
